// File that contains all the country values to process. It returns a map with all the values in the following format:
// ['key' , 'value'] = [ '<Country_ISO_Code>' , '<Country_Label>' ]

const mapCountries = new Map([
    ['AD','Andorra'],
    ['AE','E.A.U.'],
    ['AF','Afganistán'],
    ['AG','Antigua/Barbuda'],
    ['AI','Anguilla'],
    ['AL','Albania'],
    ['AM','Armenia'],
    ['AO','Angola'],
    ['AQ','Antártida'],
    ['AR','Argentina'],
    ['AS','Samoa americana'],
    ['AT','Austria'],
    ['AU','Australia'],
    ['AW','Aruba'],
    ['AX','Islas Åland'],
    ['AZ','Azerbaiyán'],
    ['BA','Bosnia-Herz.'],
    ['BB','Barbados'],
    ['BD','Bangladesh'],
    ['BE','Bélgica'],
    ['BF','Burkina Faso'],
    ['BG','Bulgaria'],
    ['BH','Bahráin'],
    ['BI','Burundi'],
    ['BJ','Benín'],
    ['BL','Azul'],
    ['BM','Bermudas'],
    ['BN','Brunéi'],
    ['BO','Bolivia'],
    ['BQ','Bonaire, Saba'],
    ['BR','Brasil'],
    ['BS','Bahamas'],
    ['BT','Bután'],
    ['BV','Islas Bouvet'],
    ['BW','Botsuana'],
    ['BY','Bielorrusia'],
    ['BZ','Belice'],
    ['CA','Canadá'],
    ['CC','Islas Cocos'],
    ['CD','República Congo'],
    ['CF','Rep.Centroafr.'],
    ['CG','República Congo'],
    ['CH','Suiza'],
    ['CI','Costa de Marfil'],
    ['CK','Islas Cook'],
    ['CL','Chile'],
    ['CM','Camerún'],
    ['CN','China'],
    ['CO','Colombia'],
    ['CR','Costa Rica'],
    ['CU','Cuba'],
    ['CV','Cabo Verde'],
    ['CW','Curaçao'],
    ['CX','Isla Christmas'],
    ['CY','Chipre'],
    ['CZ','República Checa'],
    ['DE','Alemania'],
    ['DJ','Yibuti'],
    ['DK','Dinamarca'],
    ['DM','Dominica'],
    ['DO','Rep.Dominicana'],
    ['DZ','Argelia'],
    ['EC','Ecuador'],
    ['EE','Estonia'],
    ['EG','Egipto'],
    ['EH','Sáhara occid.'],
    ['ER','Eritrea'],
    ['ES','España'],
    ['ET','Etiopía'],
    ['EU','Unión Europea'],
    ['FI','Finlandia'],
    ['FJ','Fiyi'],
    ['FK','Islas Malvinas'],
    ['FM','Micronesia'],
    ['FO','Islas Feroe'],
    ['FR','Francia'],
    ['GA','Gabón'],
    ['GB','Reino Unido'],
    ['GD','Granada'],
    ['GE','Georgia'],
    ['GF','Guayana Franc.'],
    ['GG','Guernsey'],
    ['GH','Ghana'],
    ['GI','Gibraltar'],
    ['GL','Groenlandia'],
    ['GM','Gambia'],
    ['GN','Guinea'],
    ['GP','Guadalupe'],
    ['GQ','Guinea Ecuator.'],
    ['GR','Grecia'],
    ['GS','Isl.S.Sandwich'],
    ['GT','Guatemala'],
    ['GU','Guam'],
    ['GW','Guinea-Bissau'],
    ['GY','Guyana'],
    ['HK','Hong Kong'],
    ['HM','Is.Heard/Mcdon.'],
    ['HN','Honduras'],
    ['HR','Croacia'],
    ['HT','Haití'],
    ['HU','Hungría'],
    ['ID','Indonesia'],
    ['IE','Irlanda'],
    ['IL','Israel'],
    ['IM','Isla de Man'],
    ['IN','India'],
    ['IO','Terr.br.Oc.Ind.'],
    ['IQ','Iraq'],
    ['IR','Irán'],
    ['IS','Islandia'],
    ['IT','Italia'],
    ['JE','Jersey'],
    ['JM','Jamaica'],
    ['JO','Jordania'],
    ['JP','Japón'],
    ['KE','Kenia'],
    ['KG','Kirguizistán'],
    ['KH','Camboya'],
    ['KI','Kiribati'],
    ['KM','Comoras'],
    ['KN','S.Cris.& Nieves'],
    ['KP','Corea del Norte'],
    ['KR','Corea del Sur'],
    ['KW','Kuwait'],
    ['KY','Islas Caimán'],
    ['KZ','Kazajistán'],
    ['LA','Laos'],
    ['LB','Líbano'],
    ['LC','Santa Lucía'],
    ['LI','Liechtenstein'],
    ['LK','Sri Lanka'],
    ['LR','Liberia'],
    ['LS','Lesoto'],
    ['LT','Lituania'],
    ['LU','Luxemburgo'],
    ['LV','Letonia'],
    ['LY','Libia'],
    ['MA','Marruecos'],
    ['MC','Mónaco'],
    ['MD','Moldavia'],
    ['ME','Montenegro'],
    ['MF',''],
    ['MG','Madagascar'],
    ['MH','de Isl.Marshall'],
    ['MK','Macedonia'],
    ['ML','Malí'],
    ['MM','Myanmar'],
    ['MN','Mongolia'],
    ['MO','Macao'],
    ['MP','Isl.Marianas N.'],
    ['MQ','Martinica'],
    ['MR','Mauritania'],
    ['MS','Montserrat'],
    ['MT','Malta'],
    ['MU','Mauricio (Isl.)'],
    ['MV','Maldivas'],
    ['MW','Malaui'],
    ['MX','México'],
    ['MY','Malasia'],
    ['MZ','Mozambique'],
    ['NA','Namibia'],
    ['NC','Nueva Caledonia'],
    ['NE','Níger'],
    ['NF','Islas Norfolk'],
    ['NG','Nigeria'],
    ['NI','Nicaragua'],
    ['NL','Países Bajos'],
    ['NO','Noruega'],
    ['NP','Nepal'],
    ['NR','Nauru'],
    ['NT','OTAN'],
    ['NU','Islas Niue'],
    ['NZ','Nueva Zelanda'],
    ['OM','Omán'],
    ['OR','Naranja'],
    ['PA','Panamá'],
    ['PE','Perú'],
    ['PF','Polinesia fran.'],
    ['PG','PapuaNvaGuinea'],
    ['PH','Filipinas'],
    ['PK','Pakistán'],
    ['PL','Polonia'],
    ['PM','S.Pedr.,Miquel.'],
    ['PN','Islas Pitcairn'],
    ['PR','Puerto Rico'],
    ['PS','Palestina'],
    ['PT','Portugal'],
    ['PW','Palaos'],
    ['PY','Paraguay'],
    ['QA','Qatar'],
    ['RE','Reunión'],
    ['RO','Rumanía'],
    ['RS','Serbia'],
    ['RU','Federación Rusa'],
    ['RW','Ruanda'],
    ['SA','Arabia Saudí'],
    ['SB','Islas Salomón'],
    ['SC','Seychelles'],
    ['SD','Sudán'],
    ['SE','Suecia'],
    ['SG','Singapur'],
    ['SH','Santa Helena'],
    ['SI','Eslovenia'],
    ['SJ','Svalbard'],
    ['SK','Eslovaquia'],
    ['SL','Sierra Leona'],
    ['SM','San Marino'],
    ['SN','Senegal'],
    ['SO','Somalia'],
    ['SR','Surinam'],
    ['SS','Sudán del Sur'],
    ['ST','S.Tomé,Príncipe'],
    ['SV','El Salvador'],
    ['SX','Sint Maarten'],
    ['SY','Siria'],
    ['SZ','Suazilandia'],
    ['TC','Isl.Turcas y C.'],
    ['TD','Chad'],
    ['TF','French S.Territ'],
    ['TG','Togo'],
    ['TH','Tailandia'],
    ['TJ','Tayikistán'],
    ['TK','Islas Tokelau'],
    ['TL','Timor Oriental'],
    ['TM','Turkmenistán'],
    ['TN','Túnez'],
    ['TO','Tonga'],
    ['TR','Turquía'],
    ['TT','TrinidadyTobago'],
    ['TV','Tuvalu'],
    ['TW','Taiwan'],
    ['TZ','Tanzania'],
    ['UA','Ucrania'],
    ['UG','Uganda'],
    ['UM','IslMenAlejEEUU'],
    ['UN','Naciones Unidas'],
    ['US','EE.UU.'],
    ['UY','Uruguay'],
    ['UZ','Uzbekistán'],
    ['VA','Ciudad Vaticano'],
    ['VC','San Vicente'],
    ['VE','Venezuela'],
    ['VG','Isl.Vírgenes GB'],
    ['VI','Is.Vírgenes USA'],
    ['VN','Vietnam'],
    ['VU','Vanuatu'],
    ['WF','Wallis,Futuna'],
    ['WS','Samoa Occident.'],
    ['XK','Kosovo'],
    ['YE','Yemen'],
    ['YT','Mayotte'],
    ['ZA','Sudáfrica'],
    ['ZM','Zambia'],
    ['ZW','Zimbabue']
]);

module.exports = mapCountries;